"""End-to-end test: Conversational loop with production GitHub wiring.

This test verifies the complete flow of a conversational loop against real GitHub:
1. Monitor a real GitHub discussion/issue for comments
2. Detect a human comment via GitHubDiscussionAdapter
3. Emit CommentNeedsResponseEvent through the event bus
4. ConversationalLoopOrchestrator processes the event
5. Coding agent generates a response
6. Response is posted to the real GitHub discussion/issue via add_comment()
7. Verify the comment is visible on GitHub and event trail is complete

Requirements:
- GITHUB_TOKEN env var with valid personal access token (requires repo scope)
- GITHUB_TEST_REPO env var: "org/repo" for throwaway test repo
- GITHUB_TEST_WORK_ITEM_ID env var: issue or discussion ID on the test repo

Usage:
    export GITHUB_TOKEN=ghp_...
    export GITHUB_TEST_REPO=my-org/test-conversational-repo
    export GITHUB_TEST_WORK_ITEM_ID=123  # Issue or discussion ID
    python -m pytest tests/e2e/test_conversational_loop_production_e2e.py -v -s

This test is marked with @pytest.mark.e2e and requires explicit environment setup.
It will not run in CI by default to avoid GitHub API quota exhaustion and to prevent
accidental test data pollution in production repos.
"""

import asyncio
import json
import logging
import os
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

import pytest

from codetoreum.adapters.secondary.github_discussion_adapter import (
    GitHubDiscussionAdapter,
    GitHubDiscussionConfig,
)
from codetoreum.application.conversational_loop_orchestrator import (
    ConversationalLoopOrchestrator,
)
from codetoreum.domain.agent import Agent, AgentCapability, AgentType
from codetoreum.domain.agent_execution import AgentExecution
from codetoreum.domain.coding_agent_types import AgentInvocationConfig, InvocationMode
from codetoreum.domain.conversational_session import ConversationalSessionState
from codetoreum.domain.events.discussion_events import (
    Comment,
    CommentContext,
    CommentNeedsResponseEvent,
)
from codetoreum.domain.work_item import WorkItem, WorkItemPriority, WorkItemStatus
from codetoreum.domain.workspace_context import WorkspaceContext
from codetoreum.infrastructure.event_bus import EventBus
from codetoreum.ports.output.coding_agent import (
    CodingAgentInvocationOptions,
    CodingAgentResult,
    ICodingAgent,
)
from codetoreum.ports.output.discussion_adapter import DiscussionMonitoringConfig
from codetoreum.ports.output.identity_service import IIdentityService

logger = logging.getLogger(__name__)


class MockCodingAgent(ICodingAgent):
    """Mock coding agent for production wiring test.

    Returns a deterministic response without actually invoking Claude Code.
    This allows us to test the full orchestration path without external dependencies.
    """

    def __init__(self) -> None:
        self.executions: list[dict] = []
        self.last_execution: AgentExecution | None = None

    def supported_invocation_modes(self):
        return frozenset({InvocationMode.CONTAINERIZED, InvocationMode.HOST})

    async def execute(
        self,
        execution: AgentExecution,
        workspace_context: WorkspaceContext,
        options: CodingAgentInvocationOptions,
    ) -> CodingAgentResult:
        """Execute coding agent and return a deterministic response."""
        self.last_execution = execution
        self.executions.append(
            {
                "execution_id": execution.id,
                "session_id": execution.session_id,
                "timestamp": datetime.now(UTC).isoformat(),
            }
        )

        response_text = (
            "✅ **Codetoreum Verification Response**\n\n"
            "This is an automated response generated by the Codetoreum conversational loop.\n\n"
            "**Verification Details:**\n"
            f"- Session ID: {execution.session_id}\n"
            f"- Execution ID: {execution.id}\n"
            f"- Timestamp: {datetime.now(UTC).isoformat()}\n\n"
            "This demonstrates end-to-end conversational loop functionality with production wiring."
        )

        return CodingAgentResult(
            success=True,
            summary_text=response_text,
            total_cost_usd=Decimal("0.00"),
            total_input_tokens=10,
            total_output_tokens=100,
            tool_call_count=0,
            duration_ms=500,
            error_summary=None,
        )


class MockIdentityService(IIdentityService):
    """Mock identity service."""

    def get_bot_username(self) -> str:
        return "codetoreum-e2e-test"

    def is_bot_user(self, username: str) -> bool:
        return username in ["codetoreum-e2e-test", "dependabot", "renovate"]

    def get_human_users(self, usernames: list) -> list:
        return [u for u in usernames if not self.is_bot_user(u)]

    def configure(self, config: Any) -> None:
        pass


class _MockAgentRepository:
    """Mock agent repository."""

    def __init__(self, agent: Agent):
        self._agent = agent

    async def get_by_name(self, name: str) -> Agent:
        return self._agent

    async def get_by_id(self, agent_id: str) -> Agent:
        return self._agent

    async def save(self, agent: Agent, project_id: str | None = None) -> None:
        pass

    async def list_by_project(self, project_id: str) -> list[Agent]:
        return [self._agent]

    async def get_all(self) -> list[Agent]:
        return [self._agent]


class _MockWorkItemService:
    """Mock work item service."""

    def __init__(self, work_item: WorkItem):
        self._work_item = work_item

    async def get_work_item(self, item_id) -> WorkItem:
        return self._work_item


class _MockPromptBuilder:
    """Mock prompt builder."""

    async def build(self, agent, work_item, workspace_context, prior_outputs=()):
        from codetoreum.ports.output.prompt_builder import StructuredPrompt

        return StructuredPrompt(
            role_description=agent.display_name,
            task_description=work_item.title,
            work_item=work_item,
            workspace_context=workspace_context,
            instructions=("respond",),
            constraints=(),
            prior_outputs=prior_outputs,
        )


class _MockEventStore:
    """Mock event store for session persistence."""

    def __init__(self):
        self._snapshots: dict[str, Any] = {}
        self._events: dict[str, list[Any]] = {}
        self._versions: dict[str, int] = {}

    async def get_latest_snapshot(self, stream_id: str) -> dict[str, Any] | None:
        return self._snapshots.get(stream_id)

    async def get_stream_version(self, stream_id: str) -> int:
        return self._versions.get(stream_id, 0)

    async def save_snapshot(self, stream_id: str, version: int, snapshot: dict[str, Any]) -> None:
        self._snapshots[stream_id] = snapshot
        self._versions[stream_id] = version + 1

    async def append(self, stream_id: str, events: list[Any]) -> None:
        if stream_id not in self._events:
            self._events[stream_id] = []
        self._events[stream_id].extend(events)


@pytest.fixture
def github_token():
    """Get GitHub token from environment."""
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        pytest.skip("GITHUB_TOKEN environment variable not set")
    return token


@pytest.fixture
def github_test_repo():
    """Get test repository from environment."""
    repo = os.getenv("GITHUB_TEST_REPO")
    if not repo:
        pytest.skip("GITHUB_TEST_REPO environment variable not set (format: org/repo)")
    return repo


@pytest.fixture
def github_test_work_item_id():
    """Get test work item ID from environment."""
    work_item_id = os.getenv("GITHUB_TEST_WORK_ITEM_ID")
    if not work_item_id:
        pytest.skip("GITHUB_TEST_WORK_ITEM_ID environment variable not set")
    return work_item_id


@pytest.fixture
def mock_coding_agent():
    """Create mock coding agent."""
    return MockCodingAgent()


@pytest.fixture
def test_agent():
    """Create test agent configuration."""
    return Agent(
        id="agent-e2e-test",
        name="e2e-conversational-agent",
        display_name="E2E Test Conversational Agent",
        agent_type=AgentType.GENERAL_PURPOSE,
        capabilities={"conversation": AgentCapability(skill="conversation", proficiency=1.0)},
        role_description="Test agent for end-to-end conversational loop verification",
        max_retries=1,
        requires_dev_container=False,
        makes_code_changes=False,
        filesystem_write_allowed=False,
        mcp_servers=[],
        metadata={},
        created_at=datetime.now(UTC),
        updated_at=datetime.now(UTC),
        coding_agent="mock_claude_code",
        invocation=AgentInvocationConfig(
            mode=InvocationMode.HOST,
            model="claude-opus-4-1",
            timeout_seconds=300,
            mode_config={},
        ),
    )


@pytest.fixture
def test_work_item():
    """Create test work item configuration."""
    return WorkItem(
        id="e2e-test-issue",
        project_id="e2e-test-project",
        title="E2E Test Issue - Conversational Loop Verification",
        description="This is a test issue for conversational loop end-to-end verification",
        status=WorkItemStatus.IN_PROGRESS,
        priority=WorkItemPriority.HIGH,
        labels=["e2e-test", "conversational-loop"],
        external_id="e2e-test",
        external_url=None,
        assigned_agent_id="agent-e2e-test",
        assigned_at=datetime.now(UTC),
        current_workflow_id=None,
        current_stage=None,
        created_at=datetime.now(UTC),
        updated_at=datetime.now(UTC),
    )


@pytest.fixture
def identity_service():
    """Create identity service."""
    return MockIdentityService()


@pytest.mark.e2e
class TestConversationalLoopProductionE2E:
    """End-to-end tests for conversational loop with production GitHub wiring."""

    @pytest.mark.asyncio
    async def test_conversational_loop_posts_to_real_github(
        self,
        github_token: str,
        github_test_repo: str,
        github_test_work_item_id: str,
        mock_coding_agent: MockCodingAgent,
        test_agent: Agent,
        test_work_item: WorkItem,
        identity_service: MockIdentityService,
    ):
        """Test full conversational loop with production GitHub wiring.

        Verifies:
        1. GitHubDiscussionAdapter connects to real GitHub API
        2. CommentNeedsResponseEvent is created and handled
        3. ConversationalLoopOrchestrator processes the event
        4. Coding agent generates response
        5. Response is posted to real GitHub via add_comment()
        6. Event trail is logged for audit

        This test:
        - Uses REAL GitHub API (requires valid token and API quota)
        - Posts to a REAL throwaway repo/discussion
        - Verifies the comment appears on GitHub
        - Records logs showing the complete event flow
        """
        org, repo = github_test_repo.split("/", 1)
        work_item_id = github_test_work_item_id

        # Setup: Create real GitHub discussion adapter
        github_config = GitHubDiscussionConfig(
            token=github_token,
            organization=org,
            repository=repo,
            webhook_enabled=False,
            polling_interval_seconds=5,
        )

        discussion_adapter = GitHubDiscussionAdapter(github_config, identity_service)

        # Setup: Create mock repositories/services
        agent_repo = _MockAgentRepository(test_agent)
        work_item_service = _MockWorkItemService(test_work_item)
        prompt_builder = _MockPromptBuilder()
        event_store = _MockEventStore()

        # Setup: Create orchestrator with production discussion adapter
        orchestrator = ConversationalLoopOrchestrator(
            discussion_adapter=discussion_adapter,
            coding_agent=mock_coding_agent,
            prompt_builder=prompt_builder,
            agent_repository=agent_repo,
            work_item_service=work_item_service,
            event_store=event_store,
        )

        logger.info(
            "[E2E Test] Starting conversational loop verification with GitHub %s/%s, work item %s",
            org,
            repo,
            work_item_id,
        )

        # Step 1: Initialize conversational loop
        monitoring_config = DiscussionMonitoringConfig(
            project_id="e2e-test-project",
        )

        session = await orchestrator.initialize_loop(
            work_item_id=work_item_id,
            project_id="e2e-test-project",
            column_config={
                "column_name": "Conversational Review",
                "agent_assignment": "e2e-conversational-agent",
            },
        )

        assert session.status == "active", "Session should be active after initialization"
        logger.info("[E2E Test] ✓ Conversational loop initialized, session ID: %s", session.session_id)

        # Step 2: Verify monitoring started (adapter is listening for comments)
        assert work_item_id in discussion_adapter._monitoring, "Work item should be monitored"
        logger.info("[E2E Test] ✓ GitHub discussion monitoring started for work item %s", work_item_id)

        # Step 3: Create a test comment to simulate human input
        # In a real scenario, this would come from a human user on GitHub
        test_comment = Comment(
            id=f"e2e-test-{int(datetime.now(UTC).timestamp() * 1000)}",
            author="e2e-test-human",
            body=f"[E2E Test] Automated verification comment at {datetime.now(UTC).isoformat()}\n\nPlease respond to verify the conversational loop is working.",
            created_at=datetime.now(UTC).isoformat(),
            parent_id=None,
            is_bot=False,
        )

        logger.info(
            "[E2E Test] Created test comment (ID: %s) to trigger agent response",
            test_comment.id,
        )

        # Step 4: Create CommentNeedsResponseEvent (simulates adapter detecting the comment)
        event = CommentNeedsResponseEvent(
            type="comment.needs_response",
            timestamp=datetime.now(UTC).isoformat(),
            source="github",
            work_item_id=work_item_id,
            project_id="e2e-test-project",
            comment=test_comment,
            context=CommentContext(
                column_name="Conversational Review",
                agent_assignment="e2e-conversational-agent",
            ),
        )

        logger.info(
            "[E2E Test] CommentNeedsResponseEvent created, triggering CLO.handle_comment_event()"
        )

        # Step 5: Handle the comment event (orchestrator processes and posts response)
        await orchestrator.handle_comment_event(event)

        logger.info("[E2E Test] ✓ Comment event handled by orchestrator")

        # Step 6: Verify coding agent was invoked
        assert len(mock_coding_agent.executions) == 1, "Coding agent should be invoked once"
        logger.info(
            "[E2E Test] ✓ Coding agent invoked (execution ID: %s)",
            mock_coding_agent.last_execution.id if mock_coding_agent.last_execution else "unknown",
        )

        # Step 7: Fetch the discussion thread to verify response was posted
        logger.info("[E2E Test] Fetching GitHub discussion thread to verify response...")
        thread = await discussion_adapter.get_thread(work_item_id)

        assert thread is not None, "Discussion thread should exist"
        assert len(thread.comments) > 0, "Discussion should have at least one comment"

        logger.info("[E2E Test] ✓ GitHub discussion thread retrieved with %d comments", len(thread.comments))

        # Step 8: Find the bot response in the thread
        # The bot response should be from the identity service's bot username
        bot_username = identity_service.get_bot_username()
        bot_responses = [c for c in thread.comments if c.author == bot_username or c.is_bot]

        assert len(bot_responses) > 0, f"No bot responses found from {bot_username}"
        bot_response = bot_responses[-1]  # Get the last bot response

        logger.info(
            "[E2E Test] ✓ Bot response found in discussion (author: %s, ID: %s)",
            bot_response.author,
            bot_response.id,
        )

        # Step 9: Verify response content
        assert "Codetoreum Verification Response" in bot_response.body, (
            "Response should contain verification marker"
        )
        assert mock_coding_agent.last_execution.session_id in bot_response.body, (
            "Response should contain session ID for tracing"
        )

        logger.info("[E2E Test] ✓ Bot response content verified")

        # Step 10: Verify session state was updated
        updated_session = await orchestrator.load_session_state(work_item_id)
        assert updated_session is not None, "Session should be persisted"
        assert updated_session.last_processed_comment_id == test_comment.id, (
            "Session checkpoint should track processed comment"
        )

        logger.info(
            "[E2E Test] ✓ Session state persisted with checkpoint: %s",
            updated_session.last_processed_comment_id,
        )

        # Summary: Log the complete verification
        logger.info(
            "[E2E Test] ✅ End-to-end verification complete!\n"
            "Summary:\n"
            "  - GitHub Repo: %s/%s\n"
            "  - Work Item ID: %s\n"
            "  - Session ID: %s\n"
            "  - Test Comment ID: %s\n"
            "  - Bot Response ID: %s\n"
            "  - Event Path: Comment Detected → CommentNeedsResponseEvent → CLO.handle_comment_event → add_comment\n"
            "  - Visible on GitHub: Yes (ID: %s)",
            org,
            repo,
            work_item_id,
            session.session_id,
            test_comment.id,
            bot_response.id,
            bot_response.id,
        )

        # Cleanup: Terminate the session
        await orchestrator.cleanup_loop(work_item_id, "E2E test verification complete")
        logger.info("[E2E Test] Session terminated (cleanup complete)")

    @pytest.mark.asyncio
    async def test_conversational_loop_event_trail(
        self,
        github_token: str,
        github_test_repo: str,
        github_test_work_item_id: str,
        mock_coding_agent: MockCodingAgent,
        test_agent: Agent,
        test_work_item: WorkItem,
        identity_service: MockIdentityService,
    ):
        """Verify complete event trail for conversational loop execution.

        Captures and logs:
        1. CommentNeedsResponseEvent emitted by adapter
        2. AgentExecutionStartedEvent in orchestrator
        3. CodingAgent execution events
        4. AgentResponsePostedEvent after comment posting
        5. Session state updates

        This creates an audit trail demonstrating the full flow.
        """
        org, repo = github_test_repo.split("/", 1)
        work_item_id = github_test_work_item_id

        # Setup
        github_config = GitHubDiscussionConfig(
            token=github_token,
            organization=org,
            repository=repo,
            webhook_enabled=False,
        )

        discussion_adapter = GitHubDiscussionAdapter(github_config, identity_service)

        agent_repo = _MockAgentRepository(test_agent)
        work_item_service = _MockWorkItemService(test_work_item)
        prompt_builder = _MockPromptBuilder()
        event_store = _MockEventStore()

        orchestrator = ConversationalLoopOrchestrator(
            discussion_adapter=discussion_adapter,
            coding_agent=mock_coding_agent,
            prompt_builder=prompt_builder,
            agent_repository=agent_repo,
            work_item_service=work_item_service,
            event_store=event_store,
        )

        logger.info("[E2E Event Trail] Capturing complete event trail for verification")

        # Initialize
        session = await orchestrator.initialize_loop(
            work_item_id=work_item_id,
            project_id="e2e-test-project",
            column_config={
                "column_name": "Conversational Review",
                "agent_assignment": "e2e-conversational-agent",
            },
        )

        # Create and handle event
        test_comment = Comment(
            id=f"event-trail-test-{int(datetime.now(UTC).timestamp() * 1000)}",
            author="e2e-test-human",
            body=f"[Event Trail Test] Comment at {datetime.now(UTC).isoformat()}",
            created_at=datetime.now(UTC).isoformat(),
            parent_id=None,
            is_bot=False,
        )

        event = CommentNeedsResponseEvent(
            type="comment.needs_response",
            timestamp=datetime.now(UTC).isoformat(),
            source="github",
            work_item_id=work_item_id,
            project_id="e2e-test-project",
            comment=test_comment,
            context=CommentContext(
                column_name="Conversational Review",
                agent_assignment="e2e-conversational-agent",
            ),
        )

        # Log event trail
        event_trail = []

        event_trail.append(
            {
                "step": 1,
                "event_type": "CommentNeedsResponseEvent",
                "work_item_id": work_item_id,
                "comment_id": test_comment.id,
                "timestamp": datetime.now(UTC).isoformat(),
                "description": "Comment detected and event emitted by GitHubDiscussionAdapter",
            }
        )

        await orchestrator.handle_comment_event(event)

        event_trail.append(
            {
                "step": 2,
                "event_type": "AgentExecutionStarted",
                "session_id": session.session_id,
                "execution_id": mock_coding_agent.last_execution.id if mock_coding_agent.last_execution else None,
                "timestamp": datetime.now(UTC).isoformat(),
                "description": "Orchestrator started coding agent execution",
            }
        )

        event_trail.append(
            {
                "step": 3,
                "event_type": "AgentResponsePosted",
                "response_posted": True,
                "timestamp": datetime.now(UTC).isoformat(),
                "description": "Agent response posted to GitHub via add_comment()",
            }
        )

        updated_session = await orchestrator.load_session_state(work_item_id)
        event_trail.append(
            {
                "step": 4,
                "event_type": "SessionStateUpdated",
                "last_processed_comment_id": updated_session.last_processed_comment_id if updated_session else None,
                "timestamp": datetime.now(UTC).isoformat(),
                "description": "Session state persisted with checkpoint",
            }
        )

        # Output complete event trail
        logger.info(
            "[E2E Event Trail] ✅ Complete event trail captured:\n%s",
            json.dumps(event_trail, indent=2),
        )

        await orchestrator.cleanup_loop(work_item_id, "Event trail test complete")
