"""
Configuration module for Codetoreum.

This module contains all default configuration values and constants used throughout
the application. Centralizing these values makes them easier to maintain, test,
and document.
"""

from .defaults import (
    # API Pagination
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    DEFAULT_OFFSET,
    SCHEDULER_DEFAULT_PAGE_SIZE,
    SCHEDULER_MAX_PAGE_SIZE,
    EVENTS_DEFAULT_PAGE_SIZE,
    EVENTS_MAX_PAGE_SIZE,
    WORKSPACE_DEFAULT_PAGE_SIZE,
    WORKSPACE_MAX_PAGE_SIZE,
    VERSIONS_DEFAULT_LIMIT,
    VERSIONS_MAX_LIMIT,
    # Authentication
    DEFAULT_TOKEN_EXPIRY_DAYS,
    MIN_TOKEN_LENGTH,
    DEFAULT_COOKIE_MAX_AGE_SECONDS,
    MIN_USERNAME_LENGTH,
    MAX_USERNAME_LENGTH,
    MIN_PASSWORD_LENGTH,
    MIN_API_KEY_NAME_LENGTH,
    MAX_API_KEY_NAME_LENGTH,
    # Rate Limiting
    DEFAULT_RATE_LIMIT,
    DEFAULT_RATE_LIMIT_BY_IP,
    GITHUB_RATE_LIMIT_THRESHOLD,
    MOCK_LLM_RATE_LIMIT_THRESHOLD,
    ELASTICSEARCH_RATE_LIMIT_RPS,
    # WebSocket
    DEFAULT_WS_HEARTBEAT_INTERVAL,
    DEFAULT_WS_HEARTBEAT_TIMEOUT,
    DEFAULT_WS_MAX_CONNECTIONS,
    DEFAULT_WS_MESSAGE_QUEUE_SIZE,
    DEFAULT_WS_RATE_LIMIT_MESSAGES,
    DEFAULT_WS_RATE_LIMIT_WINDOW,
    # Execution
    DEFAULT_EXECUTION_TIMEOUT,
    DEFAULT_LOG_TAIL_LIMIT,
    # Workspace
    DEFAULT_WORKSPACE_RETENTION_DAYS,
    DEFAULT_BRANCH_TITLE_MAX_LENGTH,
    # Security
    SENSITIVE_KEY_PATTERNS,
    # Environment
    VALID_ENVIRONMENTS,
    DEFAULT_ENVIRONMENT,
    # Field Length Constraints
    MAX_WORK_ITEM_ID_LENGTH,
    MAX_WORKFLOW_ID_LENGTH,
    MAX_STAGE_NAME_LENGTH,
    MAX_REASON_LENGTH,
    MAX_TITLE_LENGTH,
    MAX_DESCRIPTION_LENGTH,
    MAX_PROJECT_ID_LENGTH,
    MAX_WORKFLOW_NAME_LENGTH,
    MAX_ERROR_TYPE_LENGTH,
    MAX_ERROR_MESSAGE_LENGTH,
    MAX_CONDITION_TYPE_LENGTH,
    MAX_VALIDATION_MESSAGE_LENGTH,
    MIN_STAGES_COUNT,
    MIN_FIELD_LENGTH,
    # Server
    DEFAULT_API_PORT,
    # Redis
    DEFAULT_REDIS_STREAM_MAX_LENGTH,
    # Metrics
    DEFAULT_METRICS_AGGREGATION_WINDOW_SECONDS,
    MIN_METRICS_AGGREGATION_WINDOW_SECONDS,
    MAX_METRICS_AGGREGATION_WINDOW_SECONDS,
)

__all__ = [
    # API Pagination
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "DEFAULT_OFFSET",
    "SCHEDULER_DEFAULT_PAGE_SIZE",
    "SCHEDULER_MAX_PAGE_SIZE",
    "EVENTS_DEFAULT_PAGE_SIZE",
    "EVENTS_MAX_PAGE_SIZE",
    "WORKSPACE_DEFAULT_PAGE_SIZE",
    "WORKSPACE_MAX_PAGE_SIZE",
    "VERSIONS_DEFAULT_LIMIT",
    "VERSIONS_MAX_LIMIT",
    # Authentication
    "DEFAULT_TOKEN_EXPIRY_DAYS",
    "MIN_TOKEN_LENGTH",
    "DEFAULT_COOKIE_MAX_AGE_SECONDS",
    "MIN_USERNAME_LENGTH",
    "MAX_USERNAME_LENGTH",
    "MIN_PASSWORD_LENGTH",
    "MIN_API_KEY_NAME_LENGTH",
    "MAX_API_KEY_NAME_LENGTH",
    # Rate Limiting
    "DEFAULT_RATE_LIMIT",
    "DEFAULT_RATE_LIMIT_BY_IP",
    "GITHUB_RATE_LIMIT_THRESHOLD",
    "MOCK_LLM_RATE_LIMIT_THRESHOLD",
    "ELASTICSEARCH_RATE_LIMIT_RPS",
    # WebSocket
    "DEFAULT_WS_HEARTBEAT_INTERVAL",
    "DEFAULT_WS_HEARTBEAT_TIMEOUT",
    "DEFAULT_WS_MAX_CONNECTIONS",
    "DEFAULT_WS_MESSAGE_QUEUE_SIZE",
    "DEFAULT_WS_RATE_LIMIT_MESSAGES",
    "DEFAULT_WS_RATE_LIMIT_WINDOW",
    # Execution
    "DEFAULT_EXECUTION_TIMEOUT",
    "DEFAULT_LOG_TAIL_LIMIT",
    # Workspace
    "DEFAULT_WORKSPACE_RETENTION_DAYS",
    "DEFAULT_BRANCH_TITLE_MAX_LENGTH",
    # Security
    "SENSITIVE_KEY_PATTERNS",
    # Environment
    "VALID_ENVIRONMENTS",
    "DEFAULT_ENVIRONMENT",
    # Field Length Constraints
    "MAX_WORK_ITEM_ID_LENGTH",
    "MAX_WORKFLOW_ID_LENGTH",
    "MAX_STAGE_NAME_LENGTH",
    "MAX_REASON_LENGTH",
    "MAX_TITLE_LENGTH",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_PROJECT_ID_LENGTH",
    "MAX_WORKFLOW_NAME_LENGTH",
    "MAX_ERROR_TYPE_LENGTH",
    "MAX_ERROR_MESSAGE_LENGTH",
    "MAX_CONDITION_TYPE_LENGTH",
    "MAX_VALIDATION_MESSAGE_LENGTH",
    "MIN_STAGES_COUNT",
    "MIN_FIELD_LENGTH",
    # Server
    "DEFAULT_API_PORT",
    # Redis
    "DEFAULT_REDIS_STREAM_MAX_LENGTH",
    # Metrics
    "DEFAULT_METRICS_AGGREGATION_WINDOW_SECONDS",
    "MIN_METRICS_AGGREGATION_WINDOW_SECONDS",
    "MAX_METRICS_AGGREGATION_WINDOW_SECONDS",
]
