"""
Error ID Management for Sentry Tracking and Error Categorization

This module provides a centralized registry of error IDs used throughout
the Codetoreum application for standardized error tracking and Sentry integration.

Error IDs follow the pattern: ERR_<CATEGORY>_<DESCRIPTION>

Benefits:
- Centralized error ID definitions for easy auditing
- Type-safe error ID usage across the codebase
- Standardized categorization for error grouping in Sentry
- Documentation of all error conditions
"""

from enum import Enum


class ErrorCategory(str, Enum):
    """Error categories for Sentry tracking and grouping."""

    VALIDATION = "VALIDATION"
    AUTHENTICATION = "AUTHENTICATION"
    AUTHORIZATION = "AUTHORIZATION"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    TIMEOUT = "TIMEOUT"
    EXTERNAL_SERVICE = "EXTERNAL_SERVICE"
    INTERNAL = "INTERNAL"
    DATABASE = "DATABASE"
    CONTAINER = "CONTAINER"
    CONFIGURATION = "CONFIGURATION"
    HANDLER = "HANDLER"
    EVENT_BUS = "EVENT_BUS"
    EXECUTION = "EXECUTION"
    WORKFLOW = "WORKFLOW"
    AGENT = "AGENT"
    REPOSITORY = "REPOSITORY"
    STORAGE = "STORAGE"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    METRICS = "METRICS"
    AUDIT = "AUDIT"
    CONVERSATIONAL = "CONVERSATIONAL"
    REPAIR_CYCLE = "REPAIR_CYCLE"
    PR_REVIEW_CYCLE = "PR_REVIEW_CYCLE"
    DEBUG = "DEBUG"


class ErrorRegistry:
    """Registry of all error IDs used in the application."""

    # Validation errors
    ERR_VALIDATION_FAILED = "ERR_VALIDATION_FAILED"
    ERR_VALUE_ERROR = "ERR_VALUE_ERROR"
    ERR_INVALID_INPUT = "ERR_INVALID_INPUT"
    ERR_INVALID_STATE = "ERR_INVALID_STATE"
    ERR_SCHEMA_VALIDATION = "ERR_SCHEMA_VALIDATION"
    ERR_TYPE_VALIDATION = "ERR_TYPE_VALIDATION"

    # Authentication errors
    ERR_AUTHENTICATION_FAILED = "ERR_AUTHENTICATION_FAILED"
    ERR_INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS"
    ERR_TOKEN_INVALID = "ERR_TOKEN_INVALID"
    ERR_TOKEN_EXPIRED = "ERR_TOKEN_EXPIRED"

    # Authorization errors
    ERR_PERMISSION_DENIED = "ERR_PERMISSION_DENIED"
    ERR_UNAUTHORIZED = "ERR_UNAUTHORIZED"
    ERR_FORBIDDEN = "ERR_FORBIDDEN"

    # Not found errors
    ERR_RESOURCE_NOT_FOUND = "ERR_RESOURCE_NOT_FOUND"
    ERR_AGENT_NOT_FOUND = "ERR_AGENT_NOT_FOUND"
    ERR_EXECUTION_NOT_FOUND = "ERR_EXECUTION_NOT_FOUND"
    ERR_WORK_ITEM_NOT_FOUND = "ERR_WORK_ITEM_NOT_FOUND"
    ERR_WORKSPACE_NOT_FOUND = "ERR_WORKSPACE_NOT_FOUND"
    ERR_CONFIG_NOT_FOUND = "ERR_CONFIG_NOT_FOUND"
    ERR_PIPELINE_NOT_FOUND = "ERR_PIPELINE_NOT_FOUND"

    # Conflict errors
    ERR_RESOURCE_CONFLICT = "ERR_RESOURCE_CONFLICT"
    ERR_CONCURRENCY_CONFLICT = "ERR_CONCURRENCY_CONFLICT"
    ERR_DUPLICATE_RESOURCE = "ERR_DUPLICATE_RESOURCE"
    ERR_LOCK_CONFLICT = "ERR_LOCK_CONFLICT"

    # Timeout errors
    ERR_REQUEST_TIMEOUT = "ERR_REQUEST_TIMEOUT"
    ERR_EXECUTION_TIMEOUT = "ERR_EXECUTION_TIMEOUT"
    ERR_CONTAINER_TIMEOUT = "ERR_CONTAINER_TIMEOUT"
    ERR_EXTERNAL_SERVICE_TIMEOUT = "ERR_EXTERNAL_SERVICE_TIMEOUT"

    # External service errors
    ERR_EXTERNAL_SERVICE_ERROR = "ERR_EXTERNAL_SERVICE_ERROR"
    ERR_GITHUB_API_ERROR = "ERR_GITHUB_API_ERROR"
    ERR_LLM_PROVIDER_ERROR = "ERR_LLM_PROVIDER_ERROR"
    ERR_ELASTICSEARCH_ERROR = "ERR_ELASTICSEARCH_ERROR"
    ERR_REDIS_ERROR = "ERR_REDIS_ERROR"
    ERR_DATABASE_CONNECTION_ERROR = "ERR_DATABASE_CONNECTION_ERROR"

    # Internal errors
    ERR_UNHANDLED_EXCEPTION = "ERR_UNHANDLED_EXCEPTION"
    ERR_INTERNAL_ERROR = "ERR_INTERNAL_ERROR"
    ERR_ASSERTION_FAILED = "ERR_ASSERTION_FAILED"

    # Database errors
    ERR_DATABASE_ERROR = "ERR_DATABASE_ERROR"
    ERR_DATABASE_INTEGRITY_ERROR = "ERR_DATABASE_INTEGRITY_ERROR"
    ERR_DATABASE_QUERY_ERROR = "ERR_DATABASE_QUERY_ERROR"
    ERR_DATABASE_TRANSACTION_ERROR = "ERR_DATABASE_TRANSACTION_ERROR"
    ERR_EVENT_STORE_ERROR = "ERR_EVENT_STORE_ERROR"

    # Container errors
    ERR_CONTAINER_ERROR = "ERR_CONTAINER_ERROR"
    ERR_CONTAINER_CREATION_ERROR = "ERR_CONTAINER_CREATION_ERROR"
    ERR_CONTAINER_EXECUTION_ERROR = "ERR_CONTAINER_EXECUTION_ERROR"
    ERR_CONTAINER_NOT_FOUND = "ERR_CONTAINER_NOT_FOUND"
    ERR_CONTAINER_RECOVERY_ERROR = "ERR_CONTAINER_RECOVERY_ERROR"

    # Configuration errors
    ERR_CONFIGURATION_ERROR = "ERR_CONFIGURATION_ERROR"
    ERR_INVALID_CONFIGURATION = "ERR_INVALID_CONFIGURATION"
    ERR_MISSING_CONFIGURATION = "ERR_MISSING_CONFIGURATION"
    ERR_CONFIG_PARSING_ERROR = "ERR_CONFIG_PARSING_ERROR"

    # Handler errors
    ERR_HANDLER_REGISTRATION = "ERR_HANDLER_REGISTRATION"
    ERR_HANDLER_EXECUTION = "ERR_HANDLER_EXECUTION"
    ERR_HANDLER_NOT_FOUND = "ERR_HANDLER_NOT_FOUND"

    # Event bus errors
    ERR_EVENT_BUS_ERROR = "ERR_EVENT_BUS_ERROR"
    ERR_CALLBACK_SUBSCRIPTION = "ERR_CALLBACK_SUBSCRIPTION"
    ERR_EVENT_PUBLICATION_ERROR = "ERR_EVENT_PUBLICATION_ERROR"
    ERR_EVENT_PERSISTENCE_ERROR = "ERR_EVENT_PERSISTENCE_ERROR"

    # Execution errors
    ERR_EXECUTION_ERROR = "ERR_EXECUTION_ERROR"
    ERR_EXECUTION_FAILED = "ERR_EXECUTION_FAILED"
    ERR_EXECUTION_ALREADY_IN_PROGRESS = "ERR_EXECUTION_ALREADY_IN_PROGRESS"
    ERR_EXECUTION_CONTEXT_ERROR = "ERR_EXECUTION_CONTEXT_ERROR"

    # Workflow errors
    ERR_WORKFLOW_ERROR = "ERR_WORKFLOW_ERROR"
    ERR_WORKFLOW_TRANSITION_ERROR = "ERR_WORKFLOW_TRANSITION_ERROR"
    ERR_WORKFLOW_STAGE_ERROR = "ERR_WORKFLOW_STAGE_ERROR"
    ERR_PIPELINE_LOCK_ERROR = "ERR_PIPELINE_LOCK_ERROR"
    ERR_PIPELINE_LOCK_ACQUISITION_FAILED = "ERR_PIPELINE_LOCK_ACQUISITION_FAILED"

    # Orchestrator errors
    ERR_ORCHESTRATOR_CONFIG_LOAD = "ERR_ORCHESTRATOR_CONFIG_LOAD"
    ERR_ORCHESTRATOR_ITEM_PROCESSING = "ERR_ORCHESTRATOR_ITEM_PROCESSING"
    ERR_ORCHESTRATOR_AGENT_CONFIG_LOAD = "ERR_ORCHESTRATOR_AGENT_CONFIG_LOAD"
    ERR_ORCHESTRATOR_AGENT_VALIDATION = "ERR_ORCHESTRATOR_AGENT_VALIDATION"

    # Agent errors
    ERR_AGENT_ERROR = "ERR_AGENT_ERROR"
    ERR_AGENT_SCHEDULING_ERROR = "ERR_AGENT_SCHEDULING_ERROR"
    ERR_AGENT_EXECUTION_ERROR = "ERR_AGENT_EXECUTION_ERROR"

    # Repository errors
    ERR_REPOSITORY_ERROR = "ERR_REPOSITORY_ERROR"
    ERR_GIT_OPERATION_ERROR = "ERR_GIT_OPERATION_ERROR"
    ERR_GIT_CLONE_ERROR = "ERR_GIT_CLONE_ERROR"
    ERR_GIT_COMMIT_ERROR = "ERR_GIT_COMMIT_ERROR"
    ERR_GIT_PUSH_ERROR = "ERR_GIT_PUSH_ERROR"

    # Storage errors
    ERR_STORAGE_ERROR = "ERR_STORAGE_ERROR"
    ERR_FILE_READ_ERROR = "ERR_FILE_READ_ERROR"
    ERR_FILE_WRITE_ERROR = "ERR_FILE_WRITE_ERROR"
    ERR_FILE_NOT_FOUND = "ERR_FILE_NOT_FOUND"

    # Infrastructure errors
    ERR_INFRASTRUCTURE_ERROR = "ERR_INFRASTRUCTURE_ERROR"
    ERR_HEALTH_CHECK_FAILED = "ERR_HEALTH_CHECK_FAILED"
    ERR_SERVICE_UNAVAILABLE = "ERR_SERVICE_UNAVAILABLE"

    # Metrics errors
    ERR_METRICS_ERROR = "ERR_METRICS_ERROR"
    ERR_METRICS_COLLECTION_ERROR = "ERR_METRICS_COLLECTION_ERROR"

    # Audit errors
    ERR_AUDIT_ERROR = "ERR_AUDIT_ERROR"
    ERR_AUDIT_LOG_FAILED = "ERR_AUDIT_LOG_FAILED"

    # Conversational loop errors
    ERR_CONVERSATIONAL_MONITORING_START_FAILURE = "ERR_CONVERSATIONAL_MONITORING_START_FAILURE"
    ERR_CONVERSATIONAL_SESSION_PERSIST_FAILURE = "ERR_CONVERSATIONAL_SESSION_PERSIST_FAILURE"
    ERR_CONVERSATIONAL_SESSION_CLEANUP_FAILURE = "ERR_CONVERSATIONAL_SESSION_CLEANUP_FAILURE"
    ERR_CONVERSATIONAL_COMMENT_PROCESSING_FAILURE = "ERR_CONVERSATIONAL_COMMENT_PROCESSING_FAILURE"
    ERR_CONVERSATIONAL_LOOP_ERROR = "ERR_CONVERSATIONAL_LOOP_ERROR"

    # Repair cycle errors
    ERR_REPAIR_CYCLE_ERROR = "ERR_REPAIR_CYCLE_ERROR"
    ERR_REPAIR_CYCLE_STAGE_FAILURE = "ERR_REPAIR_CYCLE_STAGE_FAILURE"
    ERR_REPAIR_CYCLE_METRICS_ERROR = "ERR_REPAIR_CYCLE_METRICS_ERROR"
    ERR_REPAIR_CYCLE_CIRCUIT_BREAKER_OPEN = "ERR_REPAIR_CYCLE_CIRCUIT_BREAKER_OPEN"
    ERR_CHECKPOINT_ERROR = "ERR_CHECKPOINT_ERROR"
    ERR_ENVIRONMENT_REPAIR_JSON_PARSE = "ERR_ENVIRONMENT_REPAIR_JSON_PARSE"
    ERR_ENVIRONMENT_REPAIR_TIMEOUT = "ERR_ENVIRONMENT_REPAIR_TIMEOUT"

    # Debug errors
    ERR_DEBUG_MODE_IN_PRODUCTION = "ERR_DEBUG_MODE_IN_PRODUCTION"

    # Dead letter queue errors
    ERR_DEAD_LETTER_QUEUE_ERROR = "ERR_DEAD_LETTER_QUEUE_ERROR"
    ERR_DEAD_LETTER_ENQUEUE_ERROR = "ERR_DEAD_LETTER_ENQUEUE_ERROR"

    # Rate limiting errors
    ERR_RATE_LIMIT_EXCEEDED = "ERR_RATE_LIMIT_EXCEEDED"

    # Board errors
    ERR_BOARD_ERROR = "ERR_BOARD_ERROR"
    ERR_BOARD_RECONCILIATION_ERROR = "ERR_BOARD_RECONCILIATION_ERROR"
    ERR_BOARD_COLUMN_ERROR = "ERR_BOARD_COLUMN_ERROR"

    # Board event handler errors
    ERR_BOARD_EVENT_LEGACY_PAYLOAD_MISSING_KEY = "ERR_BOARD_EVENT_LEGACY_PAYLOAD_MISSING_KEY"
    ERR_BOARD_EVENT_HANDLE_COLUMN_CHANGE_FAILURE = "ERR_BOARD_EVENT_HANDLE_COLUMN_CHANGE_FAILURE"
    ERR_BOARD_EVENT_LOCK_ACQUISITION_FAILURE = "ERR_BOARD_EVENT_LOCK_ACQUISITION_FAILURE"
    ERR_BOARD_EVENT_LOCK_RELEASE_CRITICAL_FAILURE = "ERR_BOARD_EVENT_LOCK_RELEASE_CRITICAL_FAILURE"

    # Review errors
    ERR_REVIEW_ERROR = "ERR_REVIEW_ERROR"
    ERR_REVIEW_STATUS_ERROR = "ERR_REVIEW_STATUS_ERROR"
    ERR_REVIEW_CYCLE_ERROR = "ERR_REVIEW_CYCLE_ERROR"

    # PR review cycle errors
    ERR_PR_REVIEW_CYCLE_ERROR = "ERR_PR_REVIEW_CYCLE_ERROR"
    ERR_PR_REVIEW_CYCLE_SERVICE_NOT_AVAILABLE = "ERR_PR_REVIEW_CYCLE_SERVICE_NOT_AVAILABLE"
    ERR_PR_REVIEW_CYCLE_CONFIG_MISSING = "ERR_PR_REVIEW_CYCLE_CONFIG_MISSING"
    ERR_PR_REVIEW_CYCLE_STATE_RETRIEVAL_FAILURE = "ERR_PR_REVIEW_CYCLE_STATE_RETRIEVAL_FAILURE"
    ERR_PR_REVIEW_CYCLE_WORKFLOW_CONFIG_NOT_FOUND = "ERR_PR_REVIEW_CYCLE_WORKFLOW_CONFIG_NOT_FOUND"
    ERR_PR_REVIEW_CYCLE_ESCALATION_COLUMN_NOT_FOUND = "ERR_PR_REVIEW_CYCLE_ESCALATION_COLUMN_NOT_FOUND"
    ERR_PR_REVIEW_CYCLE_MAX_CYCLES_EVENT_EMIT_FAILURE = "ERR_PR_REVIEW_CYCLE_MAX_CYCLES_EVENT_EMIT_FAILURE"
    ERR_PR_REVIEW_CYCLE_WORK_ITEM_RETRIEVAL_FAILURE = "ERR_PR_REVIEW_CYCLE_WORK_ITEM_RETRIEVAL_FAILURE"
    ERR_PR_REVIEW_CYCLE_START_FAILURE = "ERR_PR_REVIEW_CYCLE_START_FAILURE"
    ERR_PR_REVIEW_CYCLE_ITEM_NOT_FOUND = "ERR_PR_REVIEW_CYCLE_ITEM_NOT_FOUND"
    ERR_PR_REVIEW_CYCLE_BOARD_SERVICE_ERROR = "ERR_PR_REVIEW_CYCLE_BOARD_SERVICE_ERROR"
    ERR_PR_REVIEW_CYCLE_MOVE_FAILURE = "ERR_PR_REVIEW_CYCLE_MOVE_FAILURE"
    ERR_PR_REVIEW_CYCLE_DISPATCH_FAILURE = "ERR_PR_REVIEW_CYCLE_DISPATCH_FAILURE"
    ERR_PR_REVIEW_CYCLE_LEGACY_PAYLOAD_MISSING_KEY = "ERR_PR_REVIEW_CYCLE_LEGACY_PAYLOAD_MISSING_KEY"
    ERR_PR_REVIEW_CYCLE_NO_ACTIVE_RUN = "ERR_PR_REVIEW_CYCLE_NO_ACTIVE_RUN"
    ERR_PR_REVIEW_CYCLE_ACTIVE_RUN_RETRIEVAL_FAILURE = "ERR_PR_REVIEW_CYCLE_ACTIVE_RUN_RETRIEVAL_FAILURE"

    # Discussion errors
    ERR_DISCUSSION_ERROR = "ERR_DISCUSSION_ERROR"
    ERR_COMMENT_ERROR = "ERR_COMMENT_ERROR"

    # Branch resolution errors
    ERR_BRANCH_RESOLUTION_ERROR = "ERR_BRANCH_RESOLUTION_ERROR"
    ERR_BRANCH_RESOLUTION_FALLBACK = "ERR_BRANCH_RESOLUTION_FALLBACK"

    @classmethod
    def get_all_error_ids(cls) -> set[str]:
        """Get all registered error IDs."""
        return {
            value
            for attr_name, value in cls.__dict__.items()
            if isinstance(value, str) and attr_name.startswith("ERR_")
        }

    @classmethod
    def validate_error_id(cls, error_id: str) -> bool:
        """Validate that an error ID is registered."""
        return error_id in cls.get_all_error_ids()


def get_error_id_category(error_id: str) -> ErrorCategory:
    """
    Determine the category of an error based on its ID.

    Args:
        error_id: The error ID to categorize

    Returns:
        ErrorCategory matching the error ID

    Raises:
        ValueError: If the error ID is not recognized
    """
    # Extract category from error ID (e.g., ERR_VALIDATION_FAILED -> VALIDATION)
    if not error_id.startswith("ERR_"):
        message = f"Invalid error ID format: {error_id}"
        raise ValueError(message)

    parts = error_id.split("_")
    if len(parts) < 2:
        message = f"Invalid error ID format: {error_id}"
        raise ValueError(message)

    # Try to find matching category
    category_name = parts[1]

    for category in ErrorCategory:
        if category.value == category_name:
            return category

    # Default to INTERNAL for unmatched errors
    return ErrorCategory.INTERNAL
