"""Port interfaces and exceptions."""

# Export all port exceptions
from codetoreum.ports.exceptions import (
    AuthenticationError,
    ConcurrencyConflictError,
    ContainerError,
    ContainerExecutionError,
    ContainerNotRunningError,
    ContainerTimeoutError,
    ConversationExpiredError,
    ConversationNotFoundError,
    EventStoreError,
    ExternalServiceError,
    ImageNotFoundError,
    LLMProviderError,
    MergeConflictError,
    MetricsError,
    NotificationError,
    PortError,
    PromptTooLongError,
    RateLimitError,
    RepositoryError,
    ResourceNotFoundError,
    StorageError,
    StreamingError,
    TicketSystemError,
    TimeoutError,
    ToolExecutionError,
    UnsupportedChannelError,
    UnsupportedFeatureError,
    ValidationError,
)

# Export output port interfaces
from codetoreum.ports.output import (
    Action,
    Attachment,
    Comment,
    ContainerHealthStatus,
    ContainerResult,
    ContainerStatus,
    DeliveryStatus,
    ExecutionContext,
    ExecutionResult,
    IContainer,
    IEventStore,
    IMetrics,
    INotifier,
    IRepository,
    ITicketSystem,
    MergeResult,
    MetricData,
    Notification,
    NotificationChannel,
    NotificationPriority,
    NotificationResult,
    RepositoryStatus,
    RichContent,
)

__all__ = [
    # Exceptions
    "PortError",
    "ResourceNotFoundError",
    "ValidationError",
    "ExternalServiceError",
    "AuthenticationError",
    "ConcurrencyConflictError",
    "RateLimitError",
    "TimeoutError",
    "TicketSystemError",
    "LLMProviderError",
    "PromptTooLongError",
    "ToolExecutionError",
    "UnsupportedFeatureError",
    "StreamingError",
    "ConversationNotFoundError",
    "ConversationExpiredError",
    "RepositoryError",
    "MergeConflictError",
    "ContainerError",
    "ContainerExecutionError",
    "ContainerTimeoutError",
    "ImageNotFoundError",
    "ContainerNotRunningError",
    "EventStoreError",
    "StorageError",
    "MetricsError",
    "NotificationError",
    "UnsupportedChannelError",
    # Output Port Interfaces
    "IContainer",
    "ContainerHealthStatus",
    "ContainerResult",
    "ContainerStatus",
    "IEventStore",
    "ExecutionContext",
    "ExecutionResult",
    "IMetrics",
    "MetricData",
    "INotifier",
    "Action",
    "Attachment",
    "DeliveryStatus",
    "Notification",
    "NotificationChannel",
    "NotificationPriority",
    "NotificationResult",
    "RichContent",
    "IRepository",
    "MergeResult",
    "RepositoryStatus",
    "ITicketSystem",
    "Comment",
]
